version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.4.2
    working_directory: ~/repo
    steps:
      - type: checkout
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix test
