version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6.1
    working_directory: ~/repo
    steps:
      - type: checkout
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix test
      - run:
          command: bash .circleci/deploy-ghpages.sh
